### ISSUE TITLE
Use a single RGB color picker instead of 3 separate switches for each color (Hyperion)

### ISSUE THREAD

**Issue by soyxan** [ericstaal/domoticz#2]
Thats it! Regarding the Hyperion plugin, can you use a single RGB color picker instead of 3 separate switches for each color?

**Comment by ericstaal** [comment]
I fixed it 18-11-2018.

If you use the old version with R G B values: Remove all the devices related to the plugin, update the plugin, toggle 'adding devices allowed' and restart the plugin

**Comment by soyxan** [comment]
Yes, works like a charm. Thanks!
