### ISSUE TITLE
Use "clear" command for turning off

### ISSUE THREAD

**Issue by soyxan** [ericstaal/domoticz#3]
I have multiple remotes for Hyperion in my home.

When I switch off Hyperion from domoticz I am not able to manipulate it from other remotes (with lower priority) and this is due to in your code you set RGB(0,0,0) when you receive a switch off command from domoticz. Instead of that you should use "clear" command as you can check in the following link:

https://hyperion-project.org/wiki/hyperion-remote-JSON-interface

**Comment by ericstaal** [comment]
@soyxan Well the priority in configurable second you can 'clear' the command when set the mode to auto iso fixed. 
fixed value with no colors is also valid :)

**Comment by soyxan** [comment]
I dont fully understan what you mean by "set mode to auto iso fixed". Anyway, when you use other interfaces (like Google Home) the only command you can send is switch off.
Based on the hyperion documentation, i think that "clear" command is the right one :)

**Comment by ericstaal** [comment]
@soyxan I made a device which allows you to set the mode: Auto, fixed or a special effect.
Auto clears the channel. Fixed uses the value from the colorpicker. 'Off' (RGB to 0,0,0) for the colorpickers is also a valid color. 

So you should use your google home to send switch off to the mode device iso the colorpicker device

**Comment by soyxan** [comment]
Yes, you are right, I had not added the "mode device". Auto works as expected.
And regarding the swicth off command, as i understand domoticz is sendind different commands for RGB(0,0,0) and for switch off, then why not use them accordingly? That is, RGB(0,0,0) will fix black color and "switch off" will clear the channel.
I am planning to modify your code in order to implement it this way as it will be more user friendly when issuing the command from Google Home (the natural way of speaking for a person in my home that does not know anything about domoticz is: "Turn on hyperion", "Set color red to hyperion", "Turn off hyperion"...) Do you think there is any inconvenience that I have not noticed in implement it this way?

**Comment by ericstaal** [comment]
Feel free to adjust it. I implemented this way since the colorpicker is only usefull in 'fixed' mode. When also using effects this gives a inconstent behaviour. I haven't found a pretty way to solve this since it is very nice to set rgb to 0,0,0 when the colorpicker is turned off in fixed mode.

I use Hyperion also for video input, but without videosignal I stel get some signals to supress this I find it easy to force it off by turning the colorpicker to off.

You can also use a DzVents script or a scene to combine the colorpicker and mode. THis script/scene can be triggered from Google. When only using fixed colors without a video input there shouldn't be a problem adjusting it.

**Comment by soyxan** [comment]
I am also using Hyperion for video in Kodi and that is why I need to (easily) be able to switch off (clear) the channel, otherwise when I play a video in Kodi Hyperion will not work after switching off from domoticz (it is forced black).
I will modify your code in order to get it working, as I think it has more sense to clear when you switch off (that is how the *official* Hyperion app for Android works, so I think it is a good idea to follow how the creators think it should behave). If you want to force a black color, you can do it selecting a black color in the color picker (and leave it on).
Please do not get this as a complain, you did a really great work creating this plugin. Thanks!
